#!/bin/bash

bold='\033[1m'
normal='\033[00m'

if [ "$1" = "-r" ]; then
  repo=$(dirs)
else
  repo=${PWD##*/}
fi

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo -en "$bold$repo$normal"; exit 0
fi

gitstatus=($(git status --porcelain | cut -d' ' -f2)) # array of lines
branch="$(git rev-parse --abbrev-ref HEAD)" || branch="unnamed branch"
branch=${branch##refs/heads/}

clean=0; del=0; changed=0; new=0;

for line in $gitstatus; do
  if [ "$line" = "D" ]; then
    del=1
  elif [ "$line" = "M" ]; then
    changed=1
  else
    new=1
  fi
done

[ -z "$line" ] && clean=1

[ $clean -eq 1 ]   && branch="$branch\033[39m✓"
[ $del -eq 1 ]     && branch="$branch\033[33m•"
[ $new -eq 1 ]     && branch="$branch\033[34m+"
[ $changed -eq 1 ] && branch="$branch\033[31m⨯"

# output
echo -en "$bold$repo$normal at $bold$branch$normal"
