#!/bin/bash

bold="\x01\033[1m\x02"
normal="\x01$(tput sgr0)\x02"

if [ "$1" = "-r" ]; then
  repo=$(dirs)
else
  repo=${PWD##*/}
fi

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo -en "$bold$repo$normal"; exit 0
fi

gitstatus=$(git status --porcelain)
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)" || branch="unnamed branch"

symbol_clean="\x01\033[39m\x02✓"  # foreground
symbol_delete="\x01\033[31m\x02⨯" # red
symbol_new="\x01\033[36m\x02+"    # cyan
symbol_change="\x01\033[33m\x02•" # yellow

for line in $gitstatus; do
  [[ $line =~ ^D ]] && symbols="$symbols$symbol_delete"
  [[ $line =~ ^M ]] && symbols="$symbols$symbol_change"
  [[ $line =~ ^\?\? ]] && symbols="$symbols$symbol_new"
done

[ -z "$symbols" ] && symbols="$symbol_clean"

# output
echo -en "$bold$repo$normal at $bold$branch $symbols$normal"
